### ISSUE TITLE
使用获取指令控制台报错

### ISSUE THREAD

**Issue by CCYellowStar** [MX233/MCInfoPlugin#2]
2022-01-24 21:06:11 W/stderr: java.net.ConnectException: Connection refused: connect
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.PlainSocketImpl.connect0(Native Method)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.Socket.connect(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.Socket.connect(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.Socket.<init>(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at java.base/java.net.Socket.<init>(Unknown Source)
2022-01-24 21:06:11 W/stderr:   at net.kronos.rkon.core.Rcon.connect(Rcon.java:64)
2022-01-24 21:06:11 W/stderr:   at net.kronos.rkon.core.Rcon.<init>(Rcon.java:36)
2022-01-24 21:06:11 W/stderr:   at org.shirakawatyu.Qc2mc.lambda$onEnable$0(Qc2mc.java:52)
2022-01-24 21:06:11 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:551)
2022-01-24 21:06:11 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:551)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
2022-01-24 21:06:11 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-01-24 21:06:11 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by MrXiaoM** [comment]
> at org.shirakawatyu.Qc2mc.lambda$onEnable$0(Qc2mc.java:52)

你确定这是 MCInfoPlugin 的报错？

**Comment by CCYellowStar** [comment]
但确实是我用了获取指令弹出来的，试了好几次，然后群里没反应

**Comment by MrXiaoM** [comment]
通过追踪找到仓库 [Kronos666/rkon-core](https://github.com/Kronos666/rkon-core)，然后 README 转跳到了 V 社的开发者社区文档。这是 steam 相关的插件的报错吧

**Comment by CCYellowStar** [comment]
那这个插件是要给什么权限吗

**Comment by MrXiaoM** [comment]
org.shirakawatyu.Qc2mc 这个包名，看起来报错的插件是这个
https://mirai.mamoe.net/topic/940
连接被拒绝了，结束这个 issue，然后好好看看帮助文档

**Comment by CCYellowStar** [comment]
主要是帮助文档说的依赖插件我也装了，但还是不能用，然后只用指令也找不到这个插件的权限名

**Comment by MX233** [comment]
我 是 傻 逼
发布的插件没加上引导，不过发了半年才有人提issue草
等会发加上引导的

**Comment by MX233** [comment]
到Releases下载1.1版本即可，大意了 草

**Comment by CCYellowStar** [comment]
草

**Comment by MX233** [comment]
> 我用获取文件的指令他把文件下载到哪里呢

缓存？没有缓存，获取了直接发出来

**Comment by MX233** [comment]
> 我现在是只能用mcskin，获取文件的好像用了没反应

mcskinfile是吧，那个是获取没处理过的原皮肤，你可以在qq直接保存的

**Comment by CCYellowStar** [comment]
但mcskin获取的不是模型分解的皮肤图片啊，是个预览

**Comment by MX233** [comment]
> 但mcskin获取的不是模型分解的皮肤图片啊，是个预览
![QQ图片20220124225344](https://user-images.githubusercontent.com/78346594/150806872-5c8a1d3d-e3c6-44bf-a54d-6b3eb997ff26.png)

**Comment by CCYellowStar** [comment]
帮助文档那里获取皮肤文件使用实例是不是指令写错了
